routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('user', 'UserController')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return redirect()->route('user.index');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\User;
use App\Http\Requests\UserRequest;
use App\Jobs\JobSendEmail;
use Mail;
class UserController extends Controller
{
    private $user;
     /**
      * initialization Dependency Injection model user
      * @param  $user
      * return $user
      */
    public function __construct(User $user)
    {
        $this->user = $user;
        $this->middleware('admin')->only('create', 'show');
    }
    /**
     * move to add user
     * return view add
     */
    public function create()
    {
        return view('admin.add');
    }
    /**
     * validate input and save new user
     * param UserRequest $request 
     * return boolean
     */
    public function store(UserRequest $request)
    {
        
        $this->user->addUsers($request->all());
        JobSendEmail::dispatch($request->all());
        flash('Thêm mới người dùng thành công');
        return redirect()->route('user.index');
    }
    /**
     * get list user and search 
     * return list user
     */
    public function index(Request $request)
    {
        $users = $this->user->getAll($request->all());
        if (empty($users['0'])) {
            return redirect()->route('user.index')->with('error', 'Không tìm thấy người dùng');
        }
        return view('admin.index', compact('users'));
    }
    /**
     * get form update user
     * param $id
     * return view update
     */
    public function show($id)
    {
        $users = $this->user->show($id);
        return view('admin.update', compact('users'));
    }
    /**
     * update user
     * param $id, $request, UserRequest
     * return view index
     */
    public function update(UserRequest $request, $id)
    {
        $this->user->updateUser($request->all(), $id);
        flash('Cập nhật người dùng thành công');
        return redirect()->route('user.index');
    }
}

resources/views/admin/add.blade.php
@extends('layouts.default')
@section('title')
    Add users
@endsection
@section('content')
    <div class="container">
        <h1>Add a new User</h1>
        <form method="POST" action="{{ route('user.store') }}" enctype="multipart/form-data">
            @csrf
            @include('users.form')
        </form>
    </div>
@endsection

resources/views/admin/index.blade.php
@extends('layouts.default')
@section('title')
    List users
@endsection
@section('content')
@include('flash::message')
<form action="{{ route('user.index') }}">
    <div class="row">
        <div class="col-4">
            <label for="">Name</label>
            <input type="text" class="form-control" name="name">
        </div>
        <div class="col-4">
            <label for="">Email</label>
            <input type="text" class="form-control" name="mai_address">
        </div>
    </div>
    <div class="row">
        <div class="col-4">
            <label for="">Address</label>
            <input type="text" class="form-control" name="address">
        </div>
        <div class="col-4">
            <label for="">Phone</label>
            <input type="text" class="form-control" name="phone">
        </div>
    </div>
    <div class="row">
        <div class="col-4">
            <input type="submit" value="Search" class="btn btn-primary">
        </div>
    </div>
</form>
@if (Session('error'))
   <h1>{{Session('error')}}</h1> 
@endif
<br>
<table class="table table-hover">
    <tr>
        <th>STT</th>
        <th>Name</th>
        <th>Email</th>
        <th>SDT</th>
        <th>Address</th>
        <th>Role</th>
        <th>Create At</th>
        <th>Action</th>
    </tr>
    @foreach ($users as $key => $us)
    <tr>
        <td>{{ $users->perPage() * ($users->currentPage() - 1) + 1 + $key }}</td>
        <td>{{ Helper::toUpperCase($us->name) }}</td>
        <td>{{ $us->mai_address }}</td>
        <td>{{ $us->phone }}</td>
        <td>{{ $us->address }}</td>
        <td>{{ User::role[$us->role] }}</td>
        <td>{{ $us->created_at }}</td>
        @can('admin')
        <td><a href="{{ route('user.update', $us->id) }}">Update</a></td>
        @endcan
    </tr>
    @endforeach
    <tr>
        <td colspan="5">{{ $users->links() }}</td>
    </tr>
</table>
@endsection

resources/views/admin/update.blade.php
@extends('layouts.default')
@section('title')
    update User
@endsection
@section('content')
    <div class="container">
        <h1>update User</h1>
        <form method="POST" action="{{ route('user.update', $users->id) }}" enctype="multipart/form-data">
            @csrf
            {{ method_field('PUT') }}
            @include('users.form')
        </form>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                    <br>
                    <a href="{{ route('user.index') }}" class="btn btn-primary">Home</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>
                                    
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

resources/views/layouts/default.blade.php
<!DOCTYPE html>
<html lang="en">
    @include('layouts.head')
<body>
    @include('layouts.header')
    @yield('content')
    @include('layouts.footer')
</body>
</html>

resources/views/layouts/footer.blade.php
<div>
    <h3>PHP training by LIFETIME technologies</h3>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

resources/views/layouts/head.blade.php
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>@yield('title')</title>
</head>

resources/views/layouts/header.blade.php
<div class="row">
    <div class="col-2"><a href="{{ route('user.index') }}" class="btn btn-primary">Danh sách người dùng</a></div>
    @can('admin')
        <div class="col-2"><a href="{{ route('user.create') }}" class="btn btn-primary">Thêm mới người dùng</a></div>
    @endcan
    <div class="col-6"></div>
    <div class="col-2">
            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                {{ Helper::toUpperCase(Auth::user()->name) }} <span class="caret"></span>
            </a>

            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{{ route('logout') }}"
                   onclick="event.preventDefault();
                                 document.getElementById('logout-form').submit();">
                    {{ __('Logout') }}
                </a>
                
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
    </div>
</div>

resources/views/users/form.blade.php
<style>
    span {
        color: red;
    }
</style>
<script>
    $(document).ready(function() {
        //jqueryemail
        @if ($errors->first('mai_address'))
            $("#ipemail").css("border", "1px solid red");
            $("#lbemail").css("color", "red");
        @endif
        //jqueryusername
        @if ($errors->first('name'))
            $("#ipusername").css("border", "1px solid red");
            $("#lbusername").css("color", "red");
        @endif
        //jqueryaddress
        @if ($errors->first('address'))
            $("#ipaddress").css("border", "1px solid red");
            $("#lbaddress").css("color", "red");
        @endif
        //jqueryphone
        @if ($errors->first('phone'))
            $("#ipphone").css("border", "1px solid red");
            $("#lbphone").css("color", "red");
        @endif
        //jquerypassword
        @if ($errors->first('password'))
            $("#ippassword").css("border", "1px solid red");
            $("#lbpassword").css("color", "red");
        @endif
        //jqueryconfirm
        @if ($errors->first('confirm_password'))
            $("#ipconfirm").css("border", "1px solid red");
            $("#lbconfirm").css("color", "red");
        @endif
    });
</script>
<div class="row">
    <div class="col">
        <label id="lbusername">Username:</label>
        <input type="text" name="name" id="ipusername" class="form-control" value="@if(isset($users->name)) {{ $users->name }} @else {{ old('name') }} @endif">
        <span>
        @if ($errors->first('name'))
            {{ $errors->first('name') }}
        @endif
        </span>
    </div>
    <div class="col">
        <label id="lbemail">Email</label>
        <input type="text" name="mai_address" id="ipemail" class="form-control" value="@if(isset($users->mai_address)) {{ $users->mai_address }} @else {{ old('mai_address') }} @endif">
        <span>
        @if ($errors->first('mai_address'))
            {{ $errors->first('mai_address') }}
        @endif
        </span>
    </div>
</div>
<div class="row">
    <div class="col">
        <label id="lbpassword">Password</label>
        <input type="password" name="password" id="ippassword" class="form-control">
        <span>
        @if ($errors->first('password'))
            {{ $errors->first('password') }}
        @endif
        </span>
    </div>
    <div class="col">
        <label id="lbconfirm">Confirm Password</label>
        <input type="password" name="confirm_password" id="ipconfirm" class="form-control">
        <span>
        @if ($errors->first('confirm_password'))
            {{ $errors->first('confirm_password') }}
        @endif
        </span>
    </div>
</div>
<div class="row">
    <div class="col">
        <label id="lbaddress">Address</label>
        <input type="text" name="address" id="ipaddress" class="form-control" value="@if(isset($users->address)) {{ $users->address }} @else {{ old('address') }} @endif">
        <span>
        @if ($errors->first('address'))
            {{ $errors->first('address') }}
        @endif
        </span>
    </div>
    <div class="col">
        <label id="lbphone">Phone</label>
        <input type="text" name="phone" id="ipphone" class="form-control" value="@if(isset($users->phone)) {{ $users->phone }} @else {{ old('phone') }} @endif">
        <span>
        @if ($errors->first('phone'))
            {{ $errors->first('phone') }}
        @endif
        </span>
    </div>
</div>
<div class="row">
    <div class="col">
        <label for="">Vai trò</label>
        <select name="role" id="" class="form-control">
            @foreach (User::role as $key => $value)
                <option value=" {{ $key }} "> {{ $value }} </option>
            @endforeach
        </select>
    </div>
</div>
<div class="row">
    <div class="col-6 mt-3">
        <input type="submit" value="@if(isset($users->id)) Update @else Add @endif" class="btn btn-primary">
    </div>
</div>